language: go
go:
  - "1.14.x"
env:
  - GO111MODULE=on
cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build
services:
  - docker
before_script:
  - go build -ldflags="-X github.com/cenkalti/tcpproxy.Version=$TRAVIS_TAG" -o tcpproxy cmd/tcpproxy/main.go
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.7
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - golangci-lint run
  - goveralls -v -race -package ./...
deploy:
  - provider: releases
    cleanup: false
    file: tcpproxy
    on:
      repo: cenkalti/tcpproxy
      tags: true
    api_key:
      secure: R6s24gP2n4v1A/TnaDePE9Bdo2Zuq1uvfwYOtTwgwgF4+aiWt13pGP8OQMFUsKlg8Y7h99rQeTH1O4WrHzD11Pe7HqcPC5K4P/SmW1pjG6fnwVcgUUl7bTS5HtbZMT/i1/xGpsqEqTrES7cxF/QFk3hJiGFfaqPTXbuWyI3K4AJ07m3mK1C6usbbNDj9e5i5sxy9PVjcHXCRQEKZaPhtmfx0xx3eJqVqKKEqRjoKWhlQiXz2BS8+l1vqOVlcQCjAE2gXZC36jf8KQYA8gvHRUW3r1RDWvDaPQkaJiEqAKvVD67dIeX5pkgLE6avWoXYxym5hOjOKhm6Ztnq5mcr8068tudFZT67DfX74i4CCubSEw+O9pRDmWEU7l8e0FcbRRVy77E1IRddgzLWNNB+rDwm9rtcnOo4P2agbSG213FA6eECFwletfPUOM8iQ4FYtkO33NcLcAoWjVOMpscQqfkdkQIsQa61rd4FV+4322aYXROigeKJQR+kY5eo63VJdeQnObscnmniDcRVrbG2vmVzuN4y/c7yjTYU5BuZX2ktXpH1HcN+XsPyMosHz7iaeWQMWqOeYl+iQ3OgkzTHNlvvD7AThIaarZiE/VFD9fb8/BG8xgW1natgxqV814x9ymYk+qIqm6gmHd3kE0ezt+BK1r1Aa2oz0LgL0zuYG1tQ=
  - provider: script
    on:
      repo: cenkalti/tcpproxy
      tags: true
    script: bash docker_push.sh
